os: osx
osx_image: xcode11.2

jobs:
  include:
    - &before
      addons:
        homebrew:
          packages:
            - c-ares
      env:
        - version: 1.16.0
      name: 1.16.0
      script: make bad
    - <<: *before
      name: 1.16.0 -lresolv
      script: make good
    - &after
      addons:
        homebrew:
          update: true
          packages:
            - c-ares
      env:
        - version: 1.16.1
      name: 1.16.1
      script: make bad
    - <<: *after
      name: 1.16.1 -lresolv
      script: make good
