os: osx
osx_image: xcode11.2
addons:
  homebrew:
    packages:
      - c-ares

jobs:
  include:
    - &1.16.0
      name: 1.16.0
      script: make bad
    - <<: *1.16.0
      name: 1.16.0 -lresolv
      script: make good
    - &1.16.1
      addons:
        homebrew:
          update: true
      name: 1.16.1
      script: make bad
    - <<: *1.16.1
      name: 1.16.1 -lresolv
      script: make good
