matrix:
  include:
    - &macos
      os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          update: true
          packages:
            - c-ares
      name: bad
      script:
        - make bad
    - <<: *macos
      name: good
      script:
        - make good
